@base_url=http://localhost:8080
POST {{base_url}}/todo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM1ODM1MzF9.bgI6b4CnULODglGGJrDjGq8294c6G5XobV5Cr33g5gc

{
  "text": "Test todo3"
}